StarIt/Models/GameModel.cs
namespace StarIt.Models;

public class GameModel
{
    public ulong GameId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public short Rate { get; set; } = 0;
    public string ImagesPath { get; set; } = string.Empty;
}

StarIt/Models/UserModel.cs
namespace StarIt.Models;

public class UserModel
{
    public Guid UserId { get; set; }
    public string Email { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public string Salt { get; set; } = string.Empty;
    public string Nickname { get; set; } = string.Empty;
    public int Status { get; set; } = 0;
}

StarIt/Models/UserRoleModel.cs
namespace StarIt.Models;

public class UserRoleModel
{
    public int RoleId { get; set; }
    public string Abbreviation { get; set; } = string.Empty;
    public string RoleName { get; set; } = string.Empty;
}

StarIt/ViewModels/GameViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StarIt.ViewModels;

public class GameViewModel
{
    [Required]
    [MaxLength(100)]
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
}

StarIt/ViewModels/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StarIt.ViewModels;

public class UserViewModel
{
    [Required]
    [EmailAddress]
    [Display(Name = "Email")]
    public string Email { get; set; } = string.Empty;
    
    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "Password")]
    public string Password { get; set; } = string.Empty;
    
    [Display(Name = "User nickname. By default it is your email address")]
    public string Nickname { get; set; } = string.Empty;
    
    public bool? RememberMe { get; set; }
}

StarIt/Areas/Admin/Controllers/GameAdmin/GameAdminController.cs
using Microsoft.AspNetCore.Mvc;
using StarIt.Attributes;
using StarIt.Bl.Game;
using StarIt.Mappers;
using StarIt.Models;
using StarIt.ViewModels;

namespace StarIt.Areas.Admin.Controllers.GameAdmin;

[Area("Admin")]
[SiteAuthorize(true)]
public class GameAdminController(IGameBl gameBl) : Controller
{
    private readonly IGameBl gameBl = gameBl;
    
    [HttpGet]
    [Route("/games/edit/{gameId?}")]
    public IActionResult ShowGameEdit(string? gameId)
    {
        return View("GameEdit", new GameViewModel());
    }

    [HttpPost]
    [Route("/games/edit")]
    public async Task<IActionResult> SaveGameCard(GameViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            if (await gameBl.CreateGame(GameModelsMapper.MapGameViewModelToDataModel(viewModel)))
                return Redirect("/");
            return View("GameEdit", viewModel);
        }
        return View("GameEdit", viewModel);
    }
}

StarIt/Areas/Admin/Controllers/HomeAdminController.cs
using Microsoft.AspNetCore.Mvc;
using StarIt.Attributes;

namespace StarIt.Areas.Admin.Controllers;

[Area("Admin")]
[SiteAuthorize(true)]
public class HomeAdminController : Controller
{
    [HttpGet]
    [Route("/admin")]
    [Route("/admin/index")]
    public IActionResult Index()
    {
        return View();
    }
}

StarIt/Controllers/Game/GameController.cs
using Microsoft.AspNetCore.Mvc;
using StarIt.Models;

namespace StarIt.Controllers.Game;

public class GameController : Controller
{
    [HttpGet]
    [Route("/games/{gameId}")]
    public IActionResult ShowGameView(string gameId)
    {
        GameModel model = new GameModel();
        return View("GameView", model);
    }

    [HttpGet]
    [Route("/games")]
    public IActionResult ShowGameList()
    {
        return View("GameList");
    }
}

StarIt/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using StarIt.Bl;
using StarIt.Models;

namespace StarIt.Controllers;

public class HomeController(ILogger<HomeController> logger, ICurrentUser currentUser) : Controller
{
    private readonly ILogger<HomeController> logger = logger;
    private readonly ICurrentUser currentUser = currentUser;

    [Route("/")]
    public IActionResult Index()
    {
        return View(currentUser.IsAuthenticated());
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

StarIt/Controllers/Login/LoginController.cs
using StarIt.Bl.Auth;
using StarIt.ViewModels;
using Microsoft.AspNetCore.Mvc;
using StarIt.Attributes;
using StarIt.Tools;

namespace StarIt.Controllers.Login;

[Controller]
public class LoginController(IAuth auth) : Controller
{
    private readonly IAuth auth = auth;

    [HttpGet]
    [Route("/login")]
    [SiteNoAuthorize]
    public IActionResult Login()
    {
        return View("Login", new UserViewModel());
    }

    [HttpGet]
    [Route("/logout")]
    [SiteAuthorize]
    public IActionResult Logout()
    {
        auth.Logout();
        return Redirect("/");
    }

    [HttpPost]
    [Route("/login")]
    [SiteNoAuthorize]
    public async Task<IActionResult> LoginPost(UserViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (await auth.Login(model.Email, model.Password, model.RememberMe == true))
                return Redirect("/");
        }
        return View("Login", model);
    }
}

StarIt/ViewComponents/AdminMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StarIt.Bl;

namespace StarIt.ViewComponents;

public class AdminMenuViewComponent(ICurrentUser currentUser) : ViewComponent
{
    private readonly ICurrentUser currentUser = currentUser;
    
    public async Task<IViewComponentResult> InvokeAsync()
    {
        bool isAdmin = await currentUser.IsAdmin();
        return View("Index", isAdmin);
    }
}

StarIt/ViewComponents/MainMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StarIt.Bl;

namespace StarIt.ViewComponents;

public class MainMenuViewComponent(ICurrentUser currentUser) : ViewComponent
{
    private readonly ICurrentUser currentUser = currentUser;

    public async Task<IViewComponentResult> InvokeAsync()
    {
        bool isLoggedIn = await currentUser.IsAuthenticated();
        return View("Index", isLoggedIn);
    }
}

StarIt/Areas/Admin/Views/GameAdmin/GameEdit.cshtml
@model StarIt.ViewModels.GameViewModel;

@{
    ViewData["Title"] = "Edit game";
}

<div>
    <form method="post" action="/games/edit">
        @Html.ValidationSummary()
        <p>
            <label>New game title</label>
            <textarea name="Title" type="text" value="@Model.Title"></textarea>
            @Html.ValidationMessageFor(m => m.Title)
        </p>
        <p>
            <label>New game description</label>
            <textarea name="Description" type="text" value="@Model.Description"></textarea>
            @Html.ValidationMessageFor(m => m.Description)
        </p>
        <p>
            <button type="submit">Add new game</button>
        </p>
    </form>
</div>

StarIt/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewData["Title"] = "Home Page adm";
}

<h1>This is admin page</h1>

StarIt/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - StarIt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/StarIt.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StarIt</a>
            <div class="navbar-expand d-flex justify-content-between right-align-text">
                <ul class="navbar-nav flex-grow-1 me-2">
                    @await Component.InvokeAsync("AdminMenu")
                </ul>
                <ul class="navbar-nav flex-grow-1 me-2">
                    @await Component.InvokeAsync("MainMenu")
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - StarIt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StarIt/Views/Game/GameEdit.cshtml
@{
    ViewData["Title"] = "Game";
}

<h1>Game edit</h1>

StarIt/Views/Game/GameView.cshtml
@{
    ViewData["Title"] = "Game";
}

<h1>Game view</h1>

StarIt/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StarIt/Views/Login/Login.cshtml
@model StarIt.ViewModels.UserViewModel

@{
    ViewData["Title"] = "Sign in";
}

<div>
    <form action="/login" method="post">
        <h1>@ViewBag.Title</h1>
        @Html.ValidationSummary()
        <p>
            <label>Email</label>
            <input name="Email" type="text" value="@Model.Email"/>
            @Html.ValidationMessageFor(m => m.Email)
        </p>
        <p>
            <label>Password</label>
            <input name="Password" type="password" value="@Model.Password"/>
            @Html.ValidationMessageFor(m => m.Password)
        </p>
        <p>
            <input type="checkbox" name="RememberMe" value="true"/> Remember me
        </p>
        <p>
            <button type="submit">Log in</button>
        </p>
    </form>
</div>

StarIt/Views/Shared/Components/AdminMenu/Index.cshtml
@model bool
    
@if (Model)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Admin" asp-controller="GameAdmin" asp-action="ShowGameEdit">Create game card</a>
    </li>
}

StarIt/Views/Shared/Components/MainMenu/Index.cshtml
@model bool

@if (Model)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Log out</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Log in</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Register">Sign up</a>
    </li>
}

StarIt/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - StarIt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/StarIt.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StarIt</a>
            <div class="navbar-expand d-flex justify-content-between right-align-text">
                <ul class="navbar-nav flex-grow-1 me-2">
                    @await Component.InvokeAsync("MainMenu")
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - StarIt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>